pipelines:
  default:
    - step:
        name: Test
        image: maven:3.3.9
        caches:
          - maven
        script:
          - cd ./FunctionSource
          - mvn -B verify
    - step:
        name: Deploy to AWS
        image: lambci/lambda:build-java8
        deployment: test
        script:
          - export AWS_ACCESS_KEY_ID=$CODERS_AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$CODERS_AWS_SECRET_ACCESS_KEY
          - sam build -b ./build -t ./template.yaml
          - sam package --template-file build/template.yaml --output-template-file packaged.yaml --s3-bucket $CODERS_AWS_BUCKET
          - sam deploy --template-file packaged.yaml --parameter-overrides Lifecycle=Development Environment=D Application=lbst --capabilities CAPABILITY_IAM --stack-name lbstSyncFunc