pipelines:
  default:
    - step:
        name: Deploy to AWS
        image: atlassian/pipelines-awscli
        script:
            - export AWS_ACCESS_KEY_ID=$CODERS_AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$CODERS_AWS_SECRET_ACCESS_KEY
            - apk add py-pip
            - pip install --user aws-sam-cli
            - codebucket="cf-templates-u6grlzjqw4qg-ap-southeast-2"
            - sam build -b ./build -t labstats.yaml
            #- sam package --template-file build/template.yaml --output-template-file packaged.yaml --s3-bucket $codebucket
            #- sam deploy --template-file packaged.yaml --parameter-overrides Lifecycle=Development Environment=D Application=lbst --capabilities CAPABILITY_IAM --stack-name lbstSyncFunc
