pipelines:
  default:
    - step:
        name: Deploy to AWS
        image: lambci/lambda:build-java8
        script:
            - export AWS_ACCESS_KEY_ID=$CODERS_AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$CODERS_AWS_SECRET_ACCESS_KEY
            - export codebucket="cf-templates-u6grlzjqw4qg-ap-southeast-2"
            - export AWS_DEFAULT_REGION=ap-southeast-2
            - sam build -b ./build -t ./labstats.yaml
            - sam package --template-file build/template.yaml --output-template-file packaged.yaml --s3-bucket $codebucket
            - sam deploy --template-file packaged.yaml --parameter-overrides Lifecycle=Development Environment=D Application=lbst --capabilities CAPABILITY_IAM --stack-name lbstSyncFunc
