version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
    commands:
      # - pip install cfn-lint
      - pip install aws-sam-cli
  build:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      # - cfn-lint -t template.yaml
      - sam build -b ./build -t ./cicd.yaml
      - sam package --template-file build/template.yaml --output-template-file packaged-template.yaml --s3-bucket ${codebucket}
artifacts:
  files:
    - '**/*'