AWSTemplateFormatVersion: 2010-09-09
Description: LabStats Get.
Parameters:
  LabStatsBucket:
    Description: S3 LabStats bucket.
    Type: String
  CodeBucket:
    Description: S3 Code bucket.
    Type: String
  CodeKey:
    Description: S3 Code bucket key.
    Type: String
  ApplicationName:
    Default: LabStats Get
    Type: String
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: Lambda
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 's3:ListBucket'
            Resource: 
            - !Sub 'arn:aws:s3:::${LabStatsBucket}' 
            - !Sub 'arn:aws:s3:::${CodeBucket}'
          - Effect: Allow
            Action:
            - 's3:GetObject'
            Resource:
            - !Sub 'arn:aws:s3:::${LabStatsBucket}/*'
            - !Sub 'arn:aws:s3:::${CodeBucket}/*'   
      RoleName: LabStats Get Role
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        CodeBucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
      FunctionName: RoomStationsQuery
      Handler: edu.sydneyuni.myuni.RoomStationsQuery
      MemorySize: 128
      Timeout: 120
      Role: !Sub ${LambdaExecutionRole.Arn}
      Runtime: java8
      Environment:
        S3_BUCKET: !Ref LabStatsBucket
  LambdaGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${LambdaFunction.Arn}
      Principal: apigateway.amazonaws.com
      SourceArn: // TODO: 
