---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'lbstCodeBuild - Labstats'
Parameters:
  RepositoryName:
    Type: String
    Default: 'labstats-sync'
  BranchName:
    Type: String
    Default: 'develop'
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  Application:
    Default: lbst
    Description: "The Application name, generally the Application Context from the SDDC. "
    Type: String
    MaxLength: 4
    MinLength: 4
Resources:
  ArtifactsBucket:
    DependsOn: CloudFormationRole # make sure that CloudFormationRole is deleted last
    #DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
  CloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'cloudformation.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
  CodeBuildRole:
    DependsOn: CloudFormationRole # make sure that CloudFormationRole is deleted last
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'codebuild.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
  AppProject:
    DependsOn: CloudFormationRole # make sure that CloudFormationRole is deleted last
    Type: 'AWS::CodeBuild::Project'
    Properties:
      BadgeEnabled: true
      Artifacts:
        Type: S3
        Location: !Ref ArtifactsBucket
      Environment:
        ComputeType: 'BUILD_GENERAL1_MEDIUM'
        Image: 'aws/codebuild/standard:1.0'
        Type: 'LINUX_CONTAINER'
        EnvironmentVariables:
        - Name: BranchName
          Value: !Ref BranchName
        - Name: codebucket
          Value: !Ref ArtifactsBucket
        - Name: ParentVPCStack
          Value: !Ref ParentVPCStack
      Name: !Sub '${AWS::StackName}-app'
      ServiceRole: !GetAtt 'CodeBuildRole.Arn'
      SourceVersion: !Sub BranchName'*'
      Source:
        Type: BITBUCKET
        Location: !Sub https://bitbucket.org/sydneyuni/${RepositoryName}
      TimeoutInMinutes: 10
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub ^refs/heads/${BranchName}*$
Outputs:
  ProjectName:
    Description: 'CodeBuild Project Name (used in other project)'
    Value: !Ref AppProject
