AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Serverless Labstats API and Sync deployed via SAM, Serverless Application\
  \ Model. \n"
Globals:
  Function:
    Timeout: 300
Outputs:
  SyncFunction:
    Description: ${SyncFunction} ARN
    Value:
      Fn::GetAtt:
      - SyncFunction
      - Arn
Parameters:
  Application:
    Default: lbst
    Description: 'The Application name, generally the Application Context from the
      SDDC. '
    MaxLength: 4
    MinLength: 4
    Type: String
  Environment:
    AllowedValues:
    - D
    - T
    - P
    ConstraintDescription: must specify D, T or P.
    Default: D
    Description: This is the environment (D, T or P)
    Type: String
  Lifecycle:
    AllowedValues:
    - Development
    - Test
    - Production
    Default: Development
    Description: This is the application Lifecycle for tagging, between Development,
      Test and Production, by default is Development
    Type: String
Resources:
  SyncFunction:
    Properties:
      CodeUri: s3://cf-templates-u6grlzjqw4qg-ap-southeast-2/4be4cdc2a95d90c543d566bba135a6ff
      Environment:
        Variables:
          LABSTATS_API_KEY: c120c47a-63cc-402c-9491-8fba2f66aa1f
      Handler: edu.sydneyuni.myuni.LabStatsSync
      MemorySize: 128
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - ssm:GetParameters
          - ssm:GetParametersByPath
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Application}/${Environment}*
          Sid: ReadSSMParameters
        Version: '2012-10-17'
      Runtime: java8
      Tags:
        Application:
          Ref: Application
        Program: Shared
      Timeout: 120
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
