AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Serverless Labstats API and Sync deployed via SAM, Serverless Application Model.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
Parameters:
  Application:
    Default: lbst
    Description: "The Application name, generally the Application Context from the SDDC."
    Type: String
    MaxLength: 4
    MinLength: 4
  Program:
    Default: Shared
    Type: String
  Environment:
    Default: C
    Description: "This is the environment (C, D, T or P)"
    Type: String
    AllowedValues: [C,D,T,P]
    ConstraintDescription: must specify C, D, T or P.
  LabStatsAPIKey:
    Default: "c120c47a-63cc-402c-9491-8fba2f66aa1f"
    Description: "This is the LabStats API Key"
    Type: String
Resources:
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      # Schedule rule in UTC.
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt SyncFunction.Arn
          Id: "SyncFunction"
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: "SyncFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
  SyncFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        Application: !Ref Application
        Program: !Ref Program
        Environment: !Ref Environment
      CodeUri: FunctionSource
      Handler: edu.sydneyuni.myuni.LabStatsSync
      Runtime: java8
      MemorySize: 170
      Timeout: 120
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          LABSTATS_API_KEY: !Sub '${LabStatsAPIKey}'
          TABLE_NAME: !Ref DynamoDBTable
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Sid: DynamoDBAccess
              Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource: !Sub '${DynamoDBTable.Arn}'
  GetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        Application: !Ref Application
        Program: !Ref Program
        Environment: !Ref Environment
      CodeUri: FunctionSource
      Handler: edu.sydneyuni.myuni.RoomStationsQuery
      Runtime: java8
      MemorySize: 170
      Timeout: 120
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Sid: DynamoDBAccess
              Effect: Allow
              Action:
                - 'dynamodb:Query'
              Resource: !Sub '${DynamoDBTable.Arn}'
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/room-stations'
            Method: GET
            RestApiId:
              Ref: GetFunctionApi
  GetFunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      EndpointConfiguration: REGIONAL
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: K
          AttributeType: N
        - AttributeName: R
          AttributeType: S
      KeySchema:
        - AttributeName: K
          KeyType: HASH
        - AttributeName: R
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: Program
          Value: Shared
Outputs:
  SyncFunction:
    Description: "SyncFunction ARN"
    Value: !GetAtt SyncFunction.Arn
  GetFunction:
    Description: "GetFunction ARN"
    Value: !GetAtt GetFunction.Arn
  GetFunctionApiEndPoint:
    Description: 'Room Stations API Endpoint'
    Value: !Sub '${GetFunctionApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${AWS::StackName}-GetFunctionApiEndPoint'
  DynamoDBTable:
    Description: "DynamoDB ARN"
    Value: !GetAtt DynamoDBTable.Arn