AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Serverless Labstats API and Sync deployed via SAM, Serverless Application Model.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
Parameters:
  ParentVPCStack:
    Description: 'Stack name of the parent VPC stack template.'
    Default: ictdevawsvpc
    Type: String
  Application:
    Default: lbst
    Description: "The Application name, generally the Application Context from the SDDC. "
    Type: String
    MaxLength: 4
    MinLength: 4
  Lifecycle:
    Description: "This is the application Lifecycle for tagging, between Development, Test and Production, by default is Development"
    Default: Development
    AllowedValues: [Development,Test,Production]
    Type: String
  Environment:
    Default: D
    Description: "This is the environment (C, D, T or P)"
    Type: String
    AllowedValues: [C,D,T,P]
    ConstraintDescription: must specify C, D, T or P.
Resources:
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      # Schedule rule in UTC.
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt SyncFunction.Arn
          Id: "SyncFunction"
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: "SyncFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
  SyncFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        Application: !Ref Application
        Program: "Shared"
      CodeUri: FunctionSource
      Handler: edu.sydneyuni.myuni.LabStatsSync
      Runtime: java8
      MemorySize: 170
      Timeout: 120
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          LABSTATS_API_KEY: "c120c47a-63cc-402c-9491-8fba2f66aa1f"
          TABLE_NAME: !Ref DynamoDBTable
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Sid: DynamoDBAccess
              Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource: !Sub '${DynamoDBTable.Arn}'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Sid: ReadSSMParameters
              Effect: Allow
              Action:
                - 'ssm:GetParameters'
                - 'ssm:GetParametersByPath'
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Application}/${Environment}*'
  GetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        Application: !Ref Application
        Program: "Shared"
      CodeUri: FunctionSource
      Handler: edu.sydneyuni.myuni.RoomStationsQuery
      Runtime: java8
      MemorySize: 170
      Timeout: 120
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Sid: DynamoDBAccess
              Effect: Allow
              Action:
                - 'dynamodb:Query'
              Resource: !Sub '${DynamoDBTable.Arn}'
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/room-stations'
            Method: get
  GetFunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      EndpointConfiguration: PRIVATE
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '0.1'
          title: !Sub ${Application}-getlabstats
        schemes:
          - https
        paths:
          /room-stations:
            get:
              produces:
                - 'application/json'
              responses:
                '200':
                  description: '200 response'
                  schema:
                    $ref: '#/definitions/Empty'
              security:
                - api_key: []
              x-amazon-apigateway-integration:
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetFunction.Arn}/invocations'
                responses:
                  default:
                    statusCode: '200'
                httpMethod: POST
                type: aws_proxy
        securityDefinitions:
          api_key:
            type: apiKey
            name: x-api-key
            in: header
        x-amazon-apigateway-policy:
          Version: "2012-10-17"
          Statement:
            - Effect: 'Deny'
              Principal: '*'
              Action: 'execute-api:Invoke'
              Resource: '*'
              #!Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${GetEventsJSONApi}/*'
              Condition:
                StringNotEquals:
                  aws:sourceVpce: 
                    'Fn::ImportValue': !Sub '${ParentVPCStack}-APIGEndpoint'
            - Effect: 'Allow'
              Principal: '*'
              Action: 'execute-api:Invoke'
              Resource: '*' 
              #arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${GetIcalLinkApi}/*'
  GetFunctionApiKey: 
    Type: AWS::ApiGateway::ApiKey
    DependsOn: GetFunctionApiStage
    Properties: 
      Description: 'API key for GetFunction'
      Enabled: true
      StageKeys:
        - RestApiId: !Ref GetFunctionApi
          StageName: !Ref Environment
  GetFunctionUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: GetFunctionApiStage
    Properties:
      ApiStages:
      - ApiId: !Ref GetFunctionApi
        Stage: !Ref Environment
      Description: GetFunction
  GetFunctionUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties : 
      KeyId: !Ref GetFunctionApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref GetFunctionUsagePlan 
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: K
          AttributeType: N
        - AttributeName: R
          AttributeType: S
      KeySchema:
        - AttributeName: K
          KeyType: HASH
        - AttributeName: R
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: Program
          Value: Shared
Outputs:
  SyncFunction:
    Description: "${SyncFunction} ARN"
    Value: !GetAtt SyncFunction.Arn
      